spring:
  session:
    store-type: jdbc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8080

